global:
    secrets:
        k8sSecretCreator:
            apiToken: ENC[AES256_GCM,data:oUhU2n6G1KF+rTS4y5PClGNNUY76kxoLRAT9uDui5QU=,iv:NrEJpUz9+W0Z6K26gcX4Hg5HXNz+z4Y3bqlHHDvYGgM=,tag:WubR1EqWy2xfgEfMCPNaTg==,type:str]
        keycloak:
            adminPassword: ENC[AES256_GCM,data:3+4+yGKoFZV4eMe5n3pt//NGWySlF24KxCzr3Ps0Fyw=,iv:JjwyYXBQAYV6PpELRtDdioTm0U6/O8fPjHpukKIyDBo=,tag:O4KxjtP+urHf8VV8CjlTIQ==,type:str]
            naavreClientSecret: ENC[AES256_GCM,data:3VfUE0ZjLNGFxF8b4/JaOswG8/gmF15EvVpjdc5BFqk=,iv:oepEz3KKNsgGqqO0XQYVFH+lJ1VRNG5iHttx/VHNgmU=,tag:5oKperELYQkKN3zy4EKQ+w==,type:str]
            #ENC[AES256_GCM,data:ADNjhKxxZccmzgTDi1vzfF9lLImcokSmiJTZ5itzScqr8FZouUFBG40OXVTjLT1CBYySENW2BnRjzk4zcjuI/PxRy8SfYG8=,iv:SPmiWY0Mj819s+/AWNEt0vMzNv3CCKKER44EVutDPmk=,tag:KF589Fiq+SZJOXCt9nR9rg==,type:comment]
            users:
                - username: ENC[AES256_GCM,data:1B34Q03xIQ==,iv:bfgPd2+BT+kUz9jBW5YkGKbq6vB8FPxwmbfzvIeaVrQ=,tag:9Bz6ng22fW4m5+47ns1v6Q==,type:str]
                  password: ENC[AES256_GCM,data:8Ckuixk2MA3qTO8BCDrljRdqkIaJnYOfeBPdC39pcs0=,iv:OmCsXRbWJR4Q3Xx70ESZYwnHTH+ldUXQ3iWUW5jcFko=,tag:IfC3u7mmil7w1eBOo2SiZA==,type:str]
                - username: ENC[AES256_GCM,data:ED6YnQ==,iv:tmQxFV0VVkbXv/fh4xkH/OtChvOmYlm/shvqnLiqGdE=,tag:zeCkFgX9Vsa+L/EKPtvueA==,type:str]
                  password: ENC[AES256_GCM,data:aSayj+MWz0vq/la8nKhL2nI4BLjcJEEubV2ylKSrbIo=,iv:WIe+UVDVguUkrjqp4MueQjAwd7FfRwnzIxynqph/OhM=,tag:vblablJa6jhJ737VX7AW1w==,type:str]
                - username: ENC[AES256_GCM,data:vbTNbZ17,iv:CSQcSh4AvB9diyGk6xo5kMDp2rnTFD9HuSnc4DS3DsA=,tag:V+40FAyYR93gbVIXcGHsKw==,type:str]
                  password: ENC[AES256_GCM,data:fCtFZkL7CGN37eoWAXjRAUWFeEOxnSYZCOIvb/cPaT0=,iv:ZoPrAqLjMwWN585vLILIEKklX4yiSWl49EMg7u7oKYU=,tag:TI05qK1aQr+RzmE9UAavUQ==,type:str]
                - username: ENC[AES256_GCM,data:RRo1Uw==,iv:9UvN6STrvKA8ulOwTbDqEmcn8R7veaDE5xJa8AK2Vt4=,tag:YYX+AvAoyOwf415AAdQ/VA==,type:str]
                  password: ENC[AES256_GCM,data:j8OC4MAqzsxP/cLpVv66e8hrw8kuiM4QmOFYJzQitK4=,iv:rVDpejm1xxuzJIDZZpVWPww7uYt7josay5ls7FpsPXI=,tag:XqNq5geiFkJwLo4xxzRwcw==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:aYA1A9qdQZ/71b22QNaUNGzGGA6CFavOUar38hZz4LM=,iv:d1F2Dem33D1PhRKdGFZ8/qzkJAYDMqGuJtRADY+8YbU=,tag:Pli/72g02KhGsTFrbg4ceA==,type:str]
        seaweedfs:
            catalogueBucket:
                access_key: ENC[AES256_GCM,data:aMKwrRfr1i/JnFpFnZ6YnhlID3WOK7lgHPBUV3LRXpU=,iv:NOyl4N1c5JRcYj733wmaJ52zoaQIzKlL/0qf0d4tacs=,tag:VcUn0+F/dwQmX2/nGpvsCg==,type:str]
                secret_key: ENC[AES256_GCM,data:xfemcK3dpMCsBeZO+rmAbKzth5Tp7HTiKbQcb7GCzgM=,iv:Ie+edCXz8P5JhmwfgbwOLpLcOU3zOYGon5GlDEUapno=,tag:MyGmpe4OO3IA/tuFZTOUHw==,type:str]
        naavreCatalogueService:
            secretKey: ENC[AES256_GCM,data:OHw4d6HufJDYoEeIo1PafEeazXkM908zsEmLrJheYfA=,iv:yVwib72zqQK8S4lahslEDQDvkygZig3NI60DaypGqyw=,tag:Jp3oFw3FsqNqTEuSdKqAhA==,type:str]
            auth:
                superuser:
                    email: ENC[AES256_GCM,data:CmmoIu7iTfMibyanv+Con/g=,iv:ARszOvVEg9XrYCiX38q7Z3Up0klHU5nkI95VvlP8rAA=,tag:iGu2L1X7F/NZSXVPYREm3g==,type:str]
                    username: ENC[AES256_GCM,data:x9+Bne4=,iv:vM6YbhBslTtMfSCHUe6h7/EOxNhJAQesjSohiGqJqT8=,tag:2N+nQLg3pzt3m3KnZw7bRg==,type:str]
                    password: ENC[AES256_GCM,data:oDnPZcTzlfrDBum2NIsUiXHObX798jIRbVSvqfWrQNg=,iv:uqgU43bypjbuM8bsnXrD/nBqol5XknvzmPb8qp3t7d0=,tag:td1qii8X69JHg4Biekni6w==,type:str]
            postgresql:
                password: ENC[AES256_GCM,data:5JSo1+n98KjGrrJI4FxGayN00QQ7pVsFC6sIpTvCb54=,iv:f9tkRkyVTjxhaPwetLzL/E9OOPQt/TnLZJG4+wIa6Ds=,tag:YHrmjDMpWuo20WVJqzas5w==,type:str]
        naavrePaasFrontend:
            secretKey: ENC[AES256_GCM,data:LUvYs8a9Xl8saS4sbXJUAnwJL0SVpz2Hj9DyJORF9eI=,iv:7OgSi4xGLJX+v1Akf34tyl0/B0ESUtYNEGiay/Cyj/E=,tag:cyHzAnO2Y26uha6YLuow1w==,type:str]
jupyterhub:
    hub:
        extraConfig:
            prometheus.py: ENC[AES256_GCM,data:EbI1SAEg7tKHXjpeZ8DExdEEVdkGFYLv8hhD+dOTGiVBXv5RcNbOr21KRwpQsIMEm34iNlxtPmJ61EB2ghncXnnYf+q48qW+S7+2pU05+VWzLOB+jI5/mSr8upnmWS0KkSF30mEd+bjfP5tXcBYW1AmpViGz9jgSVraG5ZRTNFuGLOXK7CbM30YpnWhV3cnfZMg4/uJt1319zpOZssmuUKLI9xjORWxzRi4quPLjd779nl95DgqIZQ9b+0RE3PEmbO96WLGTeW77g6ANIfvHDQjhYswnMB5iP8lIeNpZ4UpWmx9M+5ynEbYfxC18WiFsMu4MmijGuQGIn/qKL2UuzY8C8qKVkUY7H9xcGX8emRKlS/5NQczNK88rbe4WmcZZrQ==,iv:+mckWr1XYpxA5+wfaDUkoqlN0V/ctDUOPszqmL98l1A=,tag:VTuBrMejb20kIYAJ5T5Drw==,type:str]
    vlabs:
        openlab:
            #ENC[AES256_GCM,data:jmNHI2YZQRsrf9qD5MdGxThiYdWZ681O1OTSqxkZEqqgkLw8OSOjyZFqsU8j6NosMiKfufuYU6tLjoEf9fucoavyuMmFsQly,iv:8ZB9VGzlOo+v0N+lxi8UeKLzJ3tMcrAYln3JKQoSwcI=,tag:nLwzu2hBvGlwVH3Qr477AQ==,type:comment]
            configuration:
                cell_github_token: ENC[AES256_GCM,data:hyzJj4QGRXR5k0U2pWfL2bAi1Z2EqiYTRkhzWFiu3WBynyBJOH9IQCTSLruKPkmzR1ckWqUL30lOYnE5m09AhZqljXqPKvfMbqjbLoMKc/OR1t7OdGdXdPPBXbja,iv:RUgT+s5afmAtRmhjpTzVevhpKy9t82uQsJ7byWBeUJc=,tag:HGsx+VWnLNzzR+aK8UyZOw==,type:str]
                registry_token: ENC[AES256_GCM,data:x6G+cH8oee4dm2YMdfVmhRf/27xn3APmxCBDXsSqLqOH/BEHay207qAaD+shRFFYcQ4=,iv:FIKnEFZ3ZB6uxkuMvWGqHoSGtdsfzvqJ6gcYkntQNQk=,tag:/SKaDi8HsqJ7SW6+sK06lg==,type:str]
        laserfarm:
            #ENC[AES256_GCM,data:oGBs757YeUyHBUrPAjiPycWTilM2lsoEEYxN4HMPfEUNAflcHLaX+oPuznadwvK24nz+J/axSJHL6ZHpO0m5ciPnh/Gb0lRwNe8=,iv:Qo0Oj54pJ/EG9jOdz4+4yp66bnaCctmjxywobZyN2/8=,tag:mpOynUzwyPpT5DsDNn6YPw==,type:comment]
            configuration:
                cell_github_token: ENC[AES256_GCM,data:suq42cY2c5ETteX4fKLiqnKV9QUfQzyMmnHWsQx8pbUVlwcHpECo8lVVFH8gWGw8htxVq3ta/px0GLKK2OebRxmO6qwruUSkKE2wsilMpqmGAPsXDArKyCk288vm,iv:srp1gh4oqk4nuxEuL4kzTyRbRYOc4o8LjWhYLOZ/bzg=,tag:PF3QVG/O0dtgxIm1C8PevQ==,type:str]
                registry_token: ENC[AES256_GCM,data:RsqC5SHKFNXeDi4DLwU9Ok/rVoOnF9rzmKk/JgK4LT3aEq3wTwfBYuVbCQC6sY/1vBU=,iv:iGhDSmnL4vTvIhOTYxS0Wyo2oQAeJNu/jOtb2uqR7zs=,tag:H/qO4odNCg2sHBpQkADZ/w==,type:str]
        biodt-hackathon25:
            #ENC[AES256_GCM,data:Ip6KYdLCknKYer9OYB1Dvl9ygWQ2UBfPFbUxT+Fkhg7AeH3d4HCeF7Oi1mK9fAgBeH8XCstjEEhA5ONXUQYL6N8N1qWZwnudgxwv08kn+HA1HQ==,iv:Rfr1esXXLCkqTMrfdCSN20iZrVXiVbX+Mmt447AvfO0=,tag:sNBWDTpkss8F4zvasqaqXw==,type:comment]
            configuration:
                cell_github_token: ENC[AES256_GCM,data:/ORfqjA6P3v4Uerv+yl3AySc+PNmb40OBoVEIr+IkdmEMI+W1BQKf5Jzu6gjT2tjSNezmAzvizjLZ8HWEK8elEv7FusX87/H1HQMvyK++MEye7UGi0YFtwgKqw6n,iv:lnbQp8ALeDNhs94eKJW2gFbhrSUe5h61CJIQepmZAJA=,tag:G9dM/L5M84r4D/hTdbZxww==,type:str]
                registry_token: ENC[AES256_GCM,data:5PUF+AOw9WA4Exanc6ISvspvd7Fmw9HLQInwcBgNQDAzjH2GEzXg2L6nmQla5IUzLMY=,iv:a42GanHxDTjUG2hxxlZC99JKLVe1keJ6hkhgMGNt5VY=,tag:353n3Z2vuyFWktF3XXKGMA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-04-01T09:37:52Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEU/807HLY42unOGgu9ryLKAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0mqrO7yoqcA+A0BEAgEQgDt2t/l/+X0pMrV+7xOUJ6fHXQBrJHDHUkM+Nn3FxxRYCJQKq7Vcf5vqwx+12z/DhezPBQgGHIyp1EFJEQ==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-04-01T09:37:52Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQHCYFNAC0M5Kzm2MB9/KH2KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdmtRDANIK0lu29C/AgEQgDvkdYSv1hP6fQcoLH+WdM/nqIbUl60YsLi4rGuDoCTH8NFrNclJq765cUc0cRvg1Y/3JgVR9uNHq+vD9g==
          aws_profile: ""
    lastmodified: "2026-01-14T13:14:06Z"
    mac: ENC[AES256_GCM,data:tgnRWHtfgntd8mOYQcHc05+uZeYXUxM4QwwrE/S69kixgp/+xJROnpjALhApq52R5VKeSt+BgYYCFss3SaktluH3IYwvcBwCIOmI9Fpa64+pkGNYav2zlx12DF8MlSR22z+Rc5PFGkR8hHgJNqyDMB7zzx1L3I25u5shlMXgndI=,iv:uZ+SApDFhZ0HVNnrrxycoZ8KkN2p41heicetWPbIId0=,tag:tPLdtltmC0eL/U6JSEiPug==,type:str]
    pgp:
        - created_at: "2025-04-01T09:37:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAI/bkG6aLNKhZ+dMYquaTT5gijCXi0vBEoD8RRlCBqQcw
            nlQr4KjfPtRY1ZX95z+eVJT0yepAZW7JoGbFHgThQONZ7wm0te+x0KVlDjOn9SeI
            1GgBCQIQMymTP3TI3COWKwRlONWKWk69Ok9ABlF3rUiHXl2tua+xe5mXfvA1JFHh
            ubn5IEPBxw0ycLunQ2Ztb818ie7o/FM3du5z5XVnngqjgdS2AeKW5EoLt4nVd2jP
            Ex8LuzGeFXp95g==
            =NX02
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.11.0
