jupyterhub:
  vlabs:
    blue-carbon:
      enabled: false
      slug: blue-carbon
      title:  Seagrass carbon stock model Virtual Lab
      communities: [naavre]
      labels: [tutorial, marco-bolo]
      description: |
        A virtual lab to compile estimates of blue carbon storage by using essential variables and 
        satellite remote sensing at regional scales within European coastal systems .
      dirname: Seagrass carbon stock model
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-blue-carbon-jupyter
        tag: v0.1.7
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.1.7/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-blue-carbon
        registry_url: ghcr.io/naavre/cells-vl-blue-carbon
        log_queries: true
        git_public:
          repo: https://github.com/QCDIS/Seagrass_carbon_stock_model.git
          branch: main
        default_file_path: Virtual Labs/Seagrass carbon stock model/Git public/README.md
