jupyterhub:
  vlabs:
    als-tree-ind:
      enabled: false
      slug: als-tree-ind
      title:  Airborne Laser Scanning Tree Individualization Virtual Lab
      communities: [naavre]
      labels: []
      description: Identifying individual trees from airborne laser scanning data
      dirname: ALS Tree Individualization
      image:
        name: ghcr.io/naavre/flavors/naavre-fl-als-tree-ind-jupyter
        tag: v0.1.8
      configuration:
        base_image_tags_url: https://github.com/NaaVRE/flavors/releases/download/v0.1.8/base_image_tags.json
        module_mapping_url: https://raw.githubusercontent.com/QCDIS/NaaVRE-conf/main/module_mapping.json
        cell_github_url: https://github.com/NaaVRE/cells-vl-als-tree-ind
        registry_url: ghcr.io/naavre/cells-vl-als-tree-ind
        log_queries: true
