jupyterhub:
    vlabs:
        blue-carbon:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:ciQIiBmz2tPeizkEDQ+LWmd4vxTR4ZQ38muRI7quj232oNtku1xpiOg7G0rGedK3/J6BwiN6FP2DHHfbH2+5f5jfiK6hCNysrmE23OmCcMeknDPXB0+rhpi0MdSS,iv:mg7QN1OkxCkx3YQWdhe/T9seHSstu09c5Ezy2d95hUM=,tag:ViMbk86tD+3uHMXbCy1r8A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
          aws_profile: ""
    lastmodified: "2025-11-18T09:30:39Z"
    mac: ENC[AES256_GCM,data:+bt9AUsdv5vDVoqgujkPXqAACtGYLJeRwGlrce1c0l147yUghehBESWW039nP3pGIjKSMjIFf4hDcl6CCvfXcDwb5+051WEVnAAqvnHRlqsW8HF0LVNAvQrM3k2Kd/anQqLj1cDkIfZI0JZshzESyD/Qkl70ZFwSGiR/XVZewCU=,iv:shGnl9IgddjXhlXrcCrTONRF8txvpu8x0tInMhZBQBU=,tag:TClpqa31tgWOV2Qs1/Auhw==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.11.0
