jupyterhub:
    vlabs:
        als-tree-ind:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:pWNxJstbuQdiWY1Bxo4WfcX10Z8CD9d3d9HvDE7clrDTEoLLZ3P2cK8H2d1UxOHaGbXQ7op1ZAbdVohMfiMdY4ZNCfJo+uJIIclpw0TpO2AWpmbkU5ffqVaT4Evb,iv:94AVoBV/B4vH47adzhi0FuXUO00vS9baBjLa6i7itrQ=,tag:DnZlsDueqwhy8hjZ2cw3Ew==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
          aws_profile: ""
    lastmodified: "2025-11-11T14:12:46Z"
    mac: ENC[AES256_GCM,data:ZG5w3JfVDceTbBG2ccJGvqg1hUUz5XN2BVyR4bU9OMFxB/J3GJcE0V+NwDTikEcYunnTIVCDDHxhZg18tyxyLvyx8ev6qHkGrVfzc89gUzjjKYr3nAhXGByF4x6zJQGWAqJ0FiqAhOGpbql++bZBMeZ9gA070TJ8Gs+GMLop//Q=,iv:O5fyy3SB09T6VRX4YLLkxp2u88rbVV80Hb3bm5G3iVE=,tag:7bHES8vLaZVNXPkuIgU1nw==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
