jupyterhub:
    vlabs:
        biotisan-euromarec:
            configuration:
                cell_github_token: ENC[AES256_GCM,data:BCf7EN9JTMoNvzwHUF5m/mZv8AUpk5Q0NDvuts8yLawlkibpmJs3FPldmKhky54mkg17ZZb5FIbEJltUsl+62njghJ6WsGoVFHi9OeJWU4q5P0Mq2D1Gvof8x1+m,iv:twCnLaf6Ndwo6qRNO2GBuQY2YyEpJjsCYT0Z5OE8ImE=,tag:OJohs5ibTC4lPhH0GF5lzw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:050752621342:key/4680e482-89c6-4210-b541-0453aa4a41ef
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHhTmJtY4jHaV3j5UYiXyuOv54scxHoIVc/S99cT0IZ1IwEb+wEYHvw5BzS5LRYUVQe7AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMoBOteIYeaPQFvH9iAgEQgDueAqaBWDQ6xsQRgYnRzg2A3mwpH+sg4GRKyZ0rqZK1z748Wb4/WjzwQKstdCD6B99n3yjs53L/1B2tzA==
          aws_profile: ""
        - arn: arn:aws:kms:eu-central-1:050752621342:key/6a9ef814-a13a-4299-b406-2e75b3ef1554
          created_at: "2025-06-09T10:44:19Z"
          enc: AQICAHi22G6tOL2LsvF6wpMHn/yuAwEASofH+f0dK2WYCvRIlQFVbApFpEVBrEq8GqgryKrpAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgMkLsvKGO36KeDLNAgEQgDuaTh32r/f+Gkj3PWADXeVkbNhOfGaC3gpirdtfhQMP3gaXArPDXVN0QFv4cN2YTbry6yZhSnRzHWslGg==
          aws_profile: ""
    lastmodified: "2025-11-03T13:02:37Z"
    mac: ENC[AES256_GCM,data:3fRCO2vSTH5kMOIhcB2hGrPyuAaJLBXT20ZAAClbOnyXhGPaSQuYpBI3/2ZZKKCmqJVGDA2dTVpAwi5f0GLfGJPQvr8HAJsPK6WoMwqO/PLkkI78vyizYCDF0f512rlEpjYH7yNwBOVlQDHpcaWT1TOj/dq6jsz23UDQzYfZl0g=,iv:illkYmz+38YiP/RKCzwaLYoZwZyMtl3hB21lzPHfwHI=,tag:dSzJapf1EOf15VxOtC3MhQ==,type:str]
    pgp:
        - created_at: "2025-06-09T10:44:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DdjO6979FjmkSAQdAXF/xpC2U/OvjEVw/k0q1EAOpS7/mE1zRF6zoDHUhs2cw
            sMsKYprTy3FhHcuAJz356kryp/t4lWN37w5yySlCCYb78iowyIPe/N0OrhCft+Py
            1FsBCQIQPRUUP+KDp7n4aJ8DphbPEr69jZSjdZlSm1N2Wc0wcZ1kTAIQqs49dIrn
            VDDtHLzsWN5AiLUzd4JdKKOpcs4iHiTPfSj7OKqXsClIfpi3IFbi7zrot4LI
            =W+Lf
            -----END PGP MESSAGE-----
          fp: E90351D346AFCF25477190F1434316312E1CF3B1
    unencrypted_suffix: _unencrypted
    version: 3.10.2
